title: Devon Ryan # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Devon Ryan, I am a Technical Program Manager at Linkedin in the Greater New York City area. In this role I have the pleasure of working with some of the most talented minds to improve the advertising experience for our customers, while maintaining a world-class experience for our members.I am a driven, detailed-oriented Software Engineer experienced in Program Management in digital media and systems engineering. I have an innate curiosity and desire to understand how things work and a passion for walking in the shoes of the end user. This has materialized in building and deploying an IOS application after I purchased my first iPhone to learning Unity after years of playing video games.
  <br><br>
  I am a Front End Web Developer and Technical Project Manager with a passion for Video Game Development 
  <br><br>
  <a href="https://www.linkedin.com/in/devonryan">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-85214942-2 # your Google Analytics tracking ID here
