title: Devon Ryan # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a driven, detailed-oriented Software Engineer experienced in Program Management in digital media and systems engineering. I have an innate curiosity and desire to understand how things work and a passion for walking in the shoes of the end user. 
  <br><br>
  <a href="https://www.linkedin.com/in/devonryan">View My LinkedIn Profile</a>
  <br><br>
  <a href="/pdf/dr_resume.pdf" target="_blank">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-85214942-2 # your Google Analytics tracking ID here
