title: Devon Ryan # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Devon Ryan, I am a Technical Program Manager at Linkedin in the Greater New York City area. 
  <br><br>
  In this role I have the pleasure of working with some of the most talented minds to improve the advertising experience for our customers, while maintaining a world-class experience for our members.
  <br><br>
  I am a driven, detailed-oriented Software Engineer experienced in Program Management in digital media and systems engineering. I have an innate curiosity and desire to understand how things work and a passion for walking in the shoes of the end user. 
  <br><br>
  <a href="https://www.linkedin.com/in/devonryan">View My LinkedIn Profile</a> 
  <a href="/pdf/sample_presentation.pdf"> View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-85214942-2 # your Google Analytics tracking ID here
